export const fields = [
  { id: 1, name: "Computer Engineering" },
  { id: 2, name: "Electric Electronic Engineering" },
];

export const usersData = [
  {
    id: 1,
    name: "ogr1",
    surname: "ogr1",
    number: "1",
    password: "1",
    role: "STUDENT",
    field: fields[0],
  },
  {
    id: 2,
    name: "ogr2",
    surname: "ogr2",
    number: "2",
    password: "1",
    role: "STUDENT",
    field: fields[0],
  },
  {
    id: 3,
    name: "ogr3",
    surname: "ogr3",
    number: "3",
    password: "1",
    role: "STUDENT",
    field: fields[0],
  },
  {
    id: 4,
    name: "ogr4",
    surname: "ogr4",
    number: "4",
    password: "1",
    role: "STUDENT",
    field: fields[1],
  },
  {
    id: 5,
    name: "ogr5",
    surname: "ogr5",
    number: "5",
    password: "1",
    role: "STUDENT",
    field: fields[1],
  },
  {
    id: 6,
    name: "ogr6",
    surname: "ogr6",
    number: "6",
    password: "1",
    role: "STUDENT",
    field: fields[1],
  },
  {
    id: 7,
    name: "ogr7",
    surname: "ogr7",
    number: "7",
    password: "1",
    role: "STUDENT",
    field: fields[0],
  },
  {
    id: 8,
    name: "cemal",
    surname: "sakar",
    number: "8",
    password: "1",
    role: "TEACHER",
    field: fields[0],
  },
  {
    id: 9,
    name: "ali",
    surname: "veli",
    number: "9",
    password: "1",
    role: "TEACHER",
    field: fields[1],
  },
  {
    id: 10,
    name: "ahmet",
    surname: "sezer",
    number: "10",
    password: "1",
    role: "TEACHER",
    field: fields[1],
  },
  {
    id: 11,
    name: "selin",
    surname: "yıldırım",
    password: "1",
    number: "11",
    role: "TEACHER",
    field: fields[0],
  },
  {
    id: 12,
    name: "admin",
    surname: "admin",
    number: "12",
    password: "1",
    role: "ADMIN",
  },
  {
    id: 13,
    name: "canan",
    surname: "arzu",
    password: "1",
    number: "13",
    role: "TEACHER",
    field: fields[0],
  },
];

export const lessonsData = [
  {
    id: 1,
    name: "Lesson 1",
    field: fields[0],
    teacher: usersData[7],
    students: [usersData[0], usersData[1], usersData[6]],
  },
  {
    id: 2,
    name: "Lesson 2",
    field: fields[1],
    teacher: usersData[8],
    students: [usersData[3], usersData[5]],
  },
  {
    id: 3,
    name: "Lesson 3",
    field: fields[0],
    teacher: usersData[10],
    students: [usersData[0], usersData[6]],
  },
];

export const attendancesData = [
  {
    id: 1,
    date: new Date(),
    lessonCode: "ASD32",
    lesson: lessonsData[0],
    teacher: usersData[7],
    presentStudents: [usersData[0], usersData[6]],
  },
  {
    id: 2,
    date: new Date(),
    lessonCode: "QWE12",
    teacher: usersData[8],
    lesson: lessonsData[1],
    presentStudents: [usersData[4]],
  },
  {
    id: 3,
    date: new Date(new Date().setDate(new Date().getDate() - 1)), // 1 gün öncesi
    lessonCode: "RGDASA",
    teacher: usersData[8],
    lesson: lessonsData[1],
    presentStudents: [usersData[4], usersData[3], usersData[2]],
  },
  {
    id: 4,
    date: new Date(new Date().setDate(new Date().getDate() - 1)), // 1 gün öncesi
    lessonCode: "Y3HKGC",
    teacher: usersData[7],
    lesson: lessonsData[0],
    presentStudents: [usersData[4]],
  },
];
